name: delete-all-deployments

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  process-kernel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: delete-all-deployments
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: ${{ secrets.CF_PAGES_PROJECT_NAME }}
          CF_DELETE_ALIASED_DEPLOYMENTS: true
        run: |
          npm install
          npm start
